name: checkin

on:
  schedule: 
    - cron: '21 0 * * *'
  workflow_dispatch:

jobs:
  _2DFan_CheckIn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
    - name: Set up Chromium
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'
        install-chromedriver: true
    - name: Prepare module
      run: |
        pip3 install -r requirements.txt
    - name: Run Checkin
      env:
        SESSION_MAP: ${{ secrets.SESSION_MAP }}
        EZCAPTCHA_CLIENT_KEY: ${{ secrets.EZCAPTCHA_CLIENT_KEY }}
      run: |
        python main.py
